import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.sql.*;
import java.util.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author l0l
 */
public class Students extends javax.swing.JFrame {
        // global variable;
        String gender;
    /**
     * Creates new form Students
     */
    public Students() {
        initComponents();
        Connect();
        table();
    }

     // establish the connection
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    ResultSetMetaData res;
    
    // make connection
    public void Connect(){
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/grade_system_management","root","");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // display table
    private void table(){
        try{
            int i;
            pst= con.prepareStatement("select * from students");
            
            rs= pst.executeQuery();
            res= rs.getMetaData();
            i = res.getColumnCount();
            
            DefaultTableModel Df= (DefaultTableModel)stTable.getModel();
            Df.setRowCount(0);
            
            while(rs.next()){
                Vector v= new Vector();
                for(int j=1; j<=i; j++){
                    v.add(rs.getInt("id"));
                    v.add(rs.getInt("stid"));
                    v.add(rs.getString("fname"));
                    v.add(rs.getString("Lname"));
                    v.add(rs.getString("gender"));
                    v.add(rs.getString("phone"));
                    v.add(rs.getString("address"));
                    v.add(rs.getString("grade"));
                    
                }
                Df.addRow(v);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        stidtxt = new javax.swing.JTextField();
        fnametxt = new javax.swing.JTextField();
        lnametxt = new javax.swing.JTextField();
        gradetxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addresstxt = new javax.swing.JTextField();
        femalebtn = new javax.swing.JRadioButton();
        malebtn = new javax.swing.JRadioButton();
        phonetxt = new javax.swing.JTextField();
        reportbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        searchtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("STUDENT FORM");

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Student ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Firstname");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Lastname");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Parent Number");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Address");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Grade");

        stidtxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        fnametxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        lnametxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        gradetxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Gender");

        addresstxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        buttonGroup1.add(femalebtn);
        femalebtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        femalebtn.setText("Female");

        buttonGroup1.add(malebtn);
        malebtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        malebtn.setText("Male");

        phonetxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        reportbtn.setBackground(new java.awt.Color(102, 255, 204));
        reportbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reportbtn.setText("REPORT");
        reportbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportbtnActionPerformed(evt);
            }
        });

        deletebtn.setBackground(new java.awt.Color(255, 0, 0));
        deletebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deletebtn.setText("DELETE");
        deletebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        updatebtn.setBackground(new java.awt.Color(0, 102, 255));
        updatebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updatebtn.setText("UPDATE");
        updatebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        savebtn.setBackground(new java.awt.Color(51, 255, 0));
        savebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        savebtn.setText("INSERT");
        savebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        resetbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resetbtn.setText("RESET");
        resetbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(savebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updatebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deletebtn)
                .addGap(18, 18, 18)
                .addComponent(reportbtn)
                .addGap(18, 18, 18)
                .addComponent(resetbtn)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(81, 81, 81))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(48, 48, 48)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(addresstxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phonetxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lnametxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fnametxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(malebtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(femalebtn))
                            .addComponent(stidtxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gradetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(lnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(malebtn)
                    .addComponent(femalebtn)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(gradetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportbtn)
                    .addComponent(deletebtn)
                    .addComponent(updatebtn)
                    .addComponent(savebtn)
                    .addComponent(resetbtn))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Display Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        stTable.setBackground(new java.awt.Color(0, 153, 153));
        stTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        stTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Student ID", "Firstname", "Lastname", "Gender", "Parent Phone", "Address", "Grade"
            }
        ));
        stTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        searchtxt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        searchtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtxtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(501, 501, 501))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        try {
            if(stidtxt.getText().trim().isEmpty() ||
                    fnametxt.getText().trim().isEmpty() || 
                    lnametxt.getText().trim().isEmpty() || 
                    addresstxt.getText().trim().isEmpty() || 
                    phonetxt.getText().trim().isEmpty() || 
                    gradetxt.getText().trim().isEmpty()){
                
                JOptionPane.showMessageDialog(null, "All Fields are Required","Empty fields",JOptionPane.WARNING_MESSAGE);
            }else if(stidtxt.getText().length()!= 5){
                JOptionPane.showMessageDialog(null, "Student ID Should be 5 characters","Error",JOptionPane.ERROR_MESSAGE);
                stidtxt.setText("");
            }else if(phonetxt.getText().length()!=13){
                JOptionPane.showMessageDialog(null, "Phone Number has to be +(00)000-0000-00");
                phonetxt.setText("");
            }
            else{
                int id= Integer.parseInt(stidtxt.getText());
                pst = con.prepareStatement("SELECT COUNT(*) FROM students WHERE stid = ?");
                pst.setInt(1, id);
                ResultSet rs = pst.executeQuery();
                rs.next();
                int count = rs.getInt(1);
                if(count > 0){
                    JOptionPane.showMessageDialog(null, "Student ID already exists in the database", "Error", JOptionPane.ERROR_MESSAGE);
                    stidtxt.setText("");
                }else{
                    pst  = con.prepareStatement("insert into students (stid, fname,lname,gender,phone,address,grade) values (?,?,?,?,?,?,?)");
                pst.setInt(1,id);
                pst.setString(2,fnametxt.getText());
                pst.setString(3,lnametxt.getText());
                
                if(malebtn.isSelected()){
                    gender = "Male";
                }
                if(femalebtn.isSelected()){
                    gender= "Female";
                }
                pst.setString(4, gender);
                pst.setString(5,phonetxt.getText());
                pst.setString(6,addresstxt.getText());
                pst.setString(7,gradetxt.getText());
                // executeUpdate
            int rowAffected= pst.executeUpdate();
            
            if(rowAffected<=1){
                JOptionPane.showMessageDialog(null, "Saved!");
                table();
                stidtxt.setText("");
                fnametxt.setText("");
                lnametxt.setText("");
                buttonGroup1.clearSelection();
                phonetxt.setText("");
                addresstxt.setText("");
                gradetxt.setText("");
                stidtxt.requestFocus();
                
            }
                }
                //int id= Integer.parseInt(stidtxt.getText());
                   
            }
            //con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_savebtnActionPerformed
    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        try {

            DefaultTableModel Df= (DefaultTableModel)stTable.getModel();
            int selectedIndex= stTable.getSelectedRow();
            if(stidtxt.getText().trim().isEmpty() ||
                    fnametxt.getText().trim().isEmpty() || 
                    lnametxt.getText().trim().isEmpty() || 
                    addresstxt.getText().trim().isEmpty() || 
                    phonetxt.getText().trim().isEmpty() || 
                    gradetxt.getText().trim().isEmpty()){
                
                JOptionPane.showMessageDialog(null, "All Fields are Required","Empty fields",JOptionPane.WARNING_MESSAGE);
            }else if(stidtxt.getText().length()!= 5){
                JOptionPane.showMessageDialog(null, "Student ID Should be 5 characters","Error",JOptionPane.ERROR_MESSAGE);
                stidtxt.setText("");
            }else if(phonetxt.getText().length()!=13){
                JOptionPane.showMessageDialog(null, "Phone Number has to be +(00)000-0000-00");
                phonetxt.setText("");
            }
            else{
                int id= Integer.parseInt(stidtxt.getText());
                pst = con.prepareStatement("SELECT COUNT(*) FROM students WHERE stid = ?");
                pst.setInt(1, id);
                ResultSet rs = pst.executeQuery();
                rs.next();
                int value= Integer.parseInt(stidtxt.getText());
                pst  = con.prepareStatement("update students set stid=?, fname=?,lname=?,gender=?,phone=?,address=?,grade=? where id='"+value+"'");
                pst.setInt(1,id);
                pst.setString(2,fnametxt.getText());
                pst.setString(3,lnametxt.getText());
                
                if(malebtn.isSelected()){
                    gender = "Male";
                }
                else{
                    gender= "Female";
                }
                pst.setString(4, gender);
                pst.setString(5,phonetxt.getText());
                pst.setString(6,addresstxt.getText());
                pst.setString(7,gradetxt.getText());
                // executeUpdate
            int rowAffected= pst.executeUpdate();
            if(rowAffected<=1){
                JOptionPane.showMessageDialog(null, "Updated!");
                table();
                stidtxt.setText("");
                fnametxt.setText("");
                lnametxt.setText("");
                buttonGroup1.clearSelection();
                phonetxt.setText("");
                addresstxt.setText("");
                gradetxt.setText("");
                stidtxt.requestFocus();
                
                
            }
                //}
                   
            }
            //con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel Df = (DefaultTableModel) stTable.getModel();
            int selectedIndex = stTable.getSelectedRow();
            // condition if no row is selected
            if (selectedIndex != -1) {
                String value = stTable.getModel().getValueAt(selectedIndex, 0).toString();
                // check if value = id from the database is empty or not
                if (!value.trim().isEmpty()) {
                    pst = con.prepareStatement("delete from students where id=?");
                    pst.setString(1, value);
                    int rowAffected = pst.executeUpdate();
                        if (rowAffected <= 1) {
                            // double check before deleting record
                            int del = JOptionPane.showConfirmDialog(null, "Are you sure you want to Delete?","delete",JOptionPane.YES_NO_OPTION);
                            if(del==0){
                            JOptionPane.showMessageDialog(null, "Deleted!");
                            table();
                            stidtxt.setText("");
                            fnametxt.setText("");
                            lnametxt.setText("");
                            buttonGroup1.clearSelection();
                            phonetxt.setText("");
                            addresstxt.setText("");
                            gradetxt.setText("");
                            stidtxt.requestFocus();
                            }
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "No record selected or ID is empty!", "Warning", JOptionPane.WARNING_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "No record selected or ID is empty!", "Warning", JOptionPane.WARNING_MESSAGE);
                        }

            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void reportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbtnActionPerformed
        // TODO add your handling code here:
        try {
                Report report= new Report();
                report.setVisible(true);
                dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_reportbtnActionPerformed

    private void stTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stTableMouseClicked
        // TODO add your handling code here:
        try {
            DefaultTableModel Df= (DefaultTableModel)stTable.getModel();
            int selectedIndex= stTable.getSelectedRow();
            
            stidtxt.setText(Df.getValueAt(selectedIndex, 1).toString());
            fnametxt.setText(Df.getValueAt(selectedIndex, 2).toString());
            lnametxt.setText(Df.getValueAt(selectedIndex, 3).toString());
            
            String sex = (Df.getValueAt(selectedIndex, 4).toString());
            if(sex.equals("Male")){
                malebtn.setSelected(true);
            }else{
                femalebtn.setSelected(true);
            }
            phonetxt.setText(Df.getValueAt(selectedIndex, 5).toString());
            addresstxt.setText(Df.getValueAt(selectedIndex, 6).toString());
            gradetxt.setText(Df.getValueAt(selectedIndex, 7).toString());
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_stTableMouseClicked

    private void searchtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtKeyReleased
        // TODO add your handling code here:
        try {
            //DefaultTableModel Df= (DefaultTableModel)stTable.getModel();
                //int selectedIndex= stTable.getSelectedRow();
                pst  = con.prepareStatement("select * from students where stid=?");
                pst.setString(1,searchtxt.getText());
                    // executeUpdate
                rs= pst.executeQuery();
                if(rs.next()){
                    String setid = rs.getString("stid");
                    stidtxt.setText(setid);
                    String fname= rs.getString("fname");
                    fnametxt.setText(fname);
                    String lname = rs.getString("lname");
                    lnametxt.setText(lname);
                    String sex = rs.getString("gender");
                    if(sex.equals("Male")){
                    malebtn.setSelected(true);
                    }else{
                    femalebtn.setSelected(true);
                    }
                    String phone = rs.getString("phone");
                    phonetxt.setText(phone);
                    String address = rs.getString("address");
                    addresstxt.setText(address);
                    String grade = rs.getString("grade");
                    gradetxt.setText(grade);
                }
            //con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchtxtKeyReleased

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        try {
            stidtxt.setText("");
            fnametxt.setText("");
            lnametxt.setText("");
            buttonGroup1.clearSelection();
            phonetxt.setText("");
            addresstxt.setText("");
            gradetxt.setText("");
            //close the connection
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_resetbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Students().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deletebtn;
    private javax.swing.JRadioButton femalebtn;
    private javax.swing.JTextField fnametxt;
    private javax.swing.JTextField gradetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lnametxt;
    private javax.swing.JRadioButton malebtn;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JButton reportbtn;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JTable stTable;
    private javax.swing.JTextField stidtxt;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
